theme: jekyll-theme-minimal

# site wide configuration
title: Ben Dowdell
locale: en_US

# bio & social
name: Ben Dowdell
email: ben.dowdell87@gmail.com
twitter_username: bendowdell87
linkedin_username: ben-dowdell
github_username: bdowdell



