theme: jekyll-theme-minimal

# site wide configuration
title: Ben Dowdell
author: Ben Dowdell
locale: en_US

navbar-links:
  About: "about"
  Portfolio: "portfolio"
  Resume: "resume"

# bio & social
social-network-links:
  email: ben.dowdell87@gmail.com
  twitter: bendowdell87
  linkedin: ben-dowdell
  github: bdowdell

share-links-active:
  twitter: true
  linkedin: true
  github: true

url-pretty: "bendowdell.com"



