theme: jekyll-theme-minimal

# site wide configuration
title: Ben Dowdell
locale: en_US

# bio & social
name: Ben Dowdell
author: Ben Dowdell
social-network-links:
  email: ben.dowdell87@gmail.com
  twitter: bendowdell87
  linkedin: ben-dowdell
  github: bdowdell

share-links-active:
  twitter: true
  linkedin: true
  github: true

url-pretty: "bendowdell.com"



